---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: scripts.python.fn.crossplane.io
spec:
  group: python.fn.crossplane.io
  names:
    categories:
    - crossplane
    kind: Script
    listKind: ScriptList
    plural: scripts
    singular: script
  scope: Namespaced
  versions:
  - name: v1beta1
    schema:
      openAPIV3Schema:
        description: A Python script to run
        properties:
          apiVersion:
            description: 'APIVersion defines the versioned schema of this representation
              of an object. Servers should convert recognized schemas to the latest
              internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
            type: string
          script:
            description: 'A Python module that defines a function with the signature:
              compose(req: fnv1.RunFunctionRequest, rsp: fnv1.RunFunctionResponse)'
            type: string
          kind:
            description: 'Kind is a string value representing the REST resource this
              object represents. Servers may infer this from the endpoint the client
              submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
            type: string
          metadata:
            type: object
        required:
        - script
        type: object
    served: true
    storage: true
